[project]
name = "bindai"
version = "0.1.0"
description = "Core framework for BindAI"
readme = "README.md"
requires-python = ">=3.12"

dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false

authors = [
    { name = "Agim Kostari", email = "gim@bindbrain.com" }
]